/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/ulivz/Documents/ulivz/vuepress/packages/@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/ulivz/Documents/ulivz/ulivz-blog/node_modules/@vuepress/plugin-nprogress/clientRootMixin.js"
import m2 from "/Users/ulivz/Documents/ulivz/ulivz-blog/node_modules/@vuepress/plugin-medium-zoom/clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]