/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/ulivz/Documents/ulivz/vuepress/packages/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1b9ad2c6",
    path: "/2016/11/12/es6-class-and-functional-class/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-1b9ad2c6").then(next)
    },
  },
  {
    path: "/2016/11/12/es6-class-and-functional-class/index.html",
    redirect: "/2016/11/12/es6-class-and-functional-class/"
  },
  {
    path: "/_posts/2016-11-11-es6-class-and-functional-class.html",
    redirect: "/2016/11/12/es6-class-and-functional-class/"
  },
  {
    name: "v-c650be3a",
    path: "/2016/10/21/event-binding-and-bubbling/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c650be3a").then(next)
    },
  },
  {
    path: "/2016/10/21/event-binding-and-bubbling/index.html",
    redirect: "/2016/10/21/event-binding-and-bubbling/"
  },
  {
    path: "/_posts/2016-10-20-event-binding-and-bubbling.html",
    redirect: "/2016/10/21/event-binding-and-bubbling/"
  },
  {
    name: "v-1ef79381",
    path: "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-1ef79381").then(next)
    },
  },
  {
    path: "/writings/2008/07/22/梦色的光/",
    redirect: "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/"
  },
  {
    path: "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/index.html",
    redirect: "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/"
  },
  {
    path: "/_writings/2008-07-22-%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89.html",
    redirect: "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/"
  },
  {
    name: "v-73974a15",
    path: "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-73974a15").then(next)
    },
  },
  {
    path: "/writings/2008/09/13/梦韵/",
    redirect: "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/"
  },
  {
    path: "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/index.html",
    redirect: "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/"
  },
  {
    path: "/_writings/2008-09-13-%E6%A2%A6%E9%9F%B5.html",
    redirect: "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/"
  },
  {
    name: "v-7d17ff8f",
    path: "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7d17ff8f").then(next)
    },
  },
  {
    path: "/writings/2008/04/04/春之歌/",
    redirect: "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/"
  },
  {
    path: "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/index.html",
    redirect: "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/"
  },
  {
    path: "/_writings/2008-4-4-%E6%98%A5%E4%B9%8B%E6%AD%8C.html",
    redirect: "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/"
  },
  {
    name: "v-b17f4bd4",
    path: "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-b17f4bd4").then(next)
    },
  },
  {
    path: "/writings/2009/08/16/没有说过真的爱/",
    redirect: "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/"
  },
  {
    path: "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/index.html",
    redirect: "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/"
  },
  {
    path: "/_writings/2009-08-16-%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1.html",
    redirect: "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/"
  },
  {
    name: "v-c44598e2",
    path: "/2016/12/21/javascript-prototype/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c44598e2").then(next)
    },
  },
  {
    path: "/2016/12/21/javascript-prototype/index.html",
    redirect: "/2016/12/21/javascript-prototype/"
  },
  {
    path: "/_posts/2016-12-20-javascript-prototype.html",
    redirect: "/2016/12/21/javascript-prototype/"
  },
  {
    name: "v-2cb10deb",
    path: "/2018/03/28/how-to-write-a-cute-cli-part-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-2cb10deb").then(next)
    },
  },
  {
    path: "/2018/03/28/how-to-write-a-cute-cli-part-2/index.html",
    redirect: "/2018/03/28/how-to-write-a-cute-cli-part-2/"
  },
  {
    path: "/_posts/2018-3-27-how-to-write-a-cute-cli-part-2.html",
    redirect: "/2018/03/28/how-to-write-a-cute-cli-part-2/"
  },
  {
    name: "v-61f0142a",
    path: "/2018/03/16/how-to-write-a-cute-cli-part-1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-61f0142a").then(next)
    },
  },
  {
    path: "/2018/03/16/how-to-write-a-cute-cli-part-1/index.html",
    redirect: "/2018/03/16/how-to-write-a-cute-cli-part-1/"
  },
  {
    path: "/_posts/2018-3-15-how-to-write-a-cute-cli-part-1.html",
    redirect: "/2018/03/16/how-to-write-a-cute-cli-part-1/"
  },
  {
    name: "v-147f75aa",
    path: "/2018/04/13/when-you-decide-to-revert-a-merge-commit/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-147f75aa").then(next)
    },
  },
  {
    path: "/2018/04/13/when-you-decide-to-revert-a-merge-commit/index.html",
    redirect: "/2018/04/13/when-you-decide-to-revert-a-merge-commit/"
  },
  {
    path: "/_posts/2018-4-12-when-you-decide-to-revert-a-merge-commit.html",
    redirect: "/2018/04/13/when-you-decide-to-revert-a-merge-commit/"
  },
  {
    name: "v-52a0bf6a",
    path: "/2016/12/21/javascript-extend/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-52a0bf6a").then(next)
    },
  },
  {
    path: "/2016/12/21/javascript-extend/index.html",
    redirect: "/2016/12/21/javascript-extend/"
  },
  {
    path: "/_posts/2016-12-20-javascript-extend.html",
    redirect: "/2016/12/21/javascript-extend/"
  },
  {
    name: "v-5abc6379",
    path: "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-5abc6379").then(next)
    },
  },
  {
    path: "/writings/2016/02/09/漫长的纪念/",
    redirect: "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/"
  },
  {
    path: "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/index.html",
    redirect: "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/"
  },
  {
    path: "/_writings/2016-02-08-%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/",
    redirect: "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/"
  },
  {
    name: "v-378733bd",
    path: "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-378733bd").then(next)
    },
  },
  {
    path: "/writings/2010/10/18/云水河/",
    redirect: "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/"
  },
  {
    path: "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/index.html",
    redirect: "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/"
  },
  {
    path: "/_writings/2010-10-17-%E4%BA%91%E6%B0%B4%E6%B2%B3.html",
    redirect: "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2754d56").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-9e6f27fc",
    path: "/archive/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e6f27fc").then(next)
    },
    meta: {"pid":"archive","id":"archive"}
  },
  {
    path: "/archive/index.html",
    redirect: "/archive/"
  },
  {
    name: "v-78029643",
    path: "/writings/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("IndexWriting", "v-78029643").then(next)
    },
    meta: {"pid":"writing","id":"writing"}
  },
  {
    path: "/writings/index.html",
    redirect: "/writings/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tag","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-3258de12",
    path: "/tag/DOM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-3258de12").then(next)
    },
    meta: {"pid":"tag","id":"DOM"}
  },
  {
    path: "/tag/DOM/index.html",
    redirect: "/tag/DOM/"
  },
  {
    name: "v-589151f9",
    path: "/tag/散文/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-589151f9").then(next)
    },
    meta: {"pid":"tag","id":"散文"}
  },
  {
    path: "/tag/散文/index.html",
    redirect: "/tag/散文/"
  },
  {
    path: "/tag/%E6%95%A3%E6%96%87/",
    redirect: "/tag/散文/"
  },
  {
    name: "v-3259de4e",
    path: "/tag/CLI/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-3259de4e").then(next)
    },
    meta: {"pid":"tag","id":"CLI"}
  },
  {
    path: "/tag/CLI/index.html",
    redirect: "/tag/CLI/"
  },
  {
    name: "v-52d26997",
    path: "/tag/Prototype/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-52d26997").then(next)
    },
    meta: {"pid":"tag","id":"Prototype"}
  },
  {
    path: "/tag/Prototype/index.html",
    redirect: "/tag/Prototype/"
  },
  {
    name: "v-32555732",
    path: "/tag/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-32555732").then(next)
    },
    meta: {"pid":"tag","id":"Git"}
  },
  {
    path: "/tag/Git/index.html",
    redirect: "/tag/Git/"
  },
  {
    name: "v-8fdafa70",
    path: "/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-8fdafa70").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/page/2/index.html",
    redirect: "/page/2/"
  },
  {
    name: "v-5bdd03cc",
    path: "/writings/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-5bdd03cc").then(next)
    },
    meta: {"pid":"writing","id":"writing"}
  },
  {
    path: "/writings/page/2/index.html",
    redirect: "/writings/page/2/"
  },
  {
    name: "v-2ba049a4",
    path: "/tag/散文/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterClassifier", "v-2ba049a4").then(next)
    },
    meta: {"pid":"tag","id":"散文"}
  },
  {
    path: "/tag/散文/page/2/index.html",
    redirect: "/tag/散文/page/2/"
  },
  {
    path: "/tag/%E6%95%A3%E6%96%87/page/2/",
    redirect: "/tag/散文/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]