/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ULIVZ",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "ES6 Class 和 Function Class",
      "frontmatter": {
        "date": "2016-11-11T20:44:40.000Z",
        "tags": [
          "JavaScript"
        ],
        "author": "ULIVZ",
        "location": "Foshan",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2016-11-11-es6-class-and-functional-class.html",
      "relativePath": "_posts/2016-11-11-es6-class-and-functional-class.md",
      "key": "v-1b9ad2c6",
      "path": "/2016/11/12/es6-class-and-functional-class/",
      "headers": [
        {
          "level": 2,
          "title": "从一个小测试说起",
          "slug": "从一个小测试说起"
        },
        {
          "level": 3,
          "title": "enumerable",
          "slug": "enumerable"
        },
        {
          "level": 2,
          "title": "如何区分ES6 Class 和 Function Class",
          "slug": "如何区分es6-class-和-function-class"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "详解 DOM 事件绑定和事件冒泡",
      "frontmatter": {
        "date": "2016-10-20T20:44:40.000Z",
        "tags": [
          "JavaScript",
          "DOM"
        ],
        "author": "ULIVZ",
        "location": "Foshan",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2016-10-20-event-binding-and-bubbling.html",
      "relativePath": "_posts/2016-10-20-event-binding-and-bubbling.md",
      "key": "v-c650be3a",
      "path": "/2016/10/21/event-binding-and-bubbling/",
      "headers": [
        {
          "level": 2,
          "title": "绑定事件",
          "slug": "绑定事件"
        },
        {
          "level": 3,
          "title": "DOM0和DOM2",
          "slug": "dom0和dom2"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性"
        },
        {
          "level": 2,
          "title": "事件传递机制",
          "slug": "事件传递机制"
        },
        {
          "level": 2,
          "title": "事件截获",
          "slug": "事件截获"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "梦色的光",
      "frontmatter": {
        "date": "2008-7-22",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2008-07-22-%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89.html",
      "relativePath": "_writings/2008-07-22-梦色的光.md",
      "key": "v-1ef79381",
      "path": "/writings/2008/07/22/%E6%A2%A6%E8%89%B2%E7%9A%84%E5%85%89/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "title": "梦韵",
      "frontmatter": {
        "date": "2008-9-13",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2008-09-13-%E6%A2%A6%E9%9F%B5.html",
      "relativePath": "_writings/2008-09-13-梦韵.md",
      "key": "v-73974a15",
      "path": "/writings/2008/09/13/%E6%A2%A6%E9%9F%B5/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "title": "春之歌",
      "frontmatter": {
        "date": "2008-4-4",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2008-4-4-%E6%98%A5%E4%B9%8B%E6%AD%8C.html",
      "relativePath": "_writings/2008-4-4-春之歌.md",
      "key": "v-7d17ff8f",
      "path": "/writings/2008/04/04/%E6%98%A5%E4%B9%8B%E6%AD%8C/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "title": "没有说过真的爱",
      "frontmatter": {
        "date": "2009-08-16T00:00:00.000Z",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2009-08-16-%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1.html",
      "relativePath": "_writings/2009-08-16-没有说过真的爱.md",
      "key": "v-b17f4bd4",
      "path": "/writings/2009/08/16/%E6%B2%A1%E6%9C%89%E8%AF%B4%E8%BF%87%E7%9C%9F%E7%9A%84%E7%88%B1/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "title": "万物皆空之 JavaScript 原型",
      "frontmatter": {
        "date": "2016-12-20T20:44:40.000Z",
        "tags": [
          "JavaScript"
        ],
        "author": "ULIVZ",
        "location": "Foshan",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2016-12-20-javascript-prototype.html",
      "relativePath": "_posts/2016-12-20-javascript-prototype.md",
      "key": "v-c44598e2",
      "path": "/2016/12/21/javascript-prototype/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "引入：普通对象与函数对象",
          "slug": "引入：普通对象与函数对象"
        },
        {
          "level": 2,
          "title": "进阶：prototype 和 __proto__",
          "slug": "进阶：prototype-和-proto"
        },
        {
          "level": 2,
          "title": "重点：原型链",
          "slug": "重点：原型链"
        },
        {
          "level": 2,
          "title": "终极：原型链图",
          "slug": "终极：原型链图"
        },
        {
          "level": 2,
          "title": "调料：constructor",
          "slug": "调料：constructor"
        },
        {
          "level": 2,
          "title": "补充： JavaScript中的6大内置（函数）对象的原型继承",
          "slug": "补充：-javascript中的6大内置（函数）对象的原型继承"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "如何开发一个可爱的CLI（二）",
      "frontmatter": {
        "date": "2018-03-27T20:44:40.000Z",
        "tags": [
          "CLI"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-3-27-how-to-write-a-cute-cli-part-2.html",
      "relativePath": "_posts/2018-3-27-how-to-write-a-cute-cli-part-2.md",
      "key": "v-2cb10deb",
      "path": "/2018/03/28/how-to-write-a-cute-cli-part-2/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "分析",
          "slug": "分析"
        },
        {
          "level": 2,
          "title": "实施",
          "slug": "实施"
        },
        {
          "level": 3,
          "title": "任务一",
          "slug": "任务一"
        },
        {
          "level": 3,
          "title": "任务二",
          "slug": "任务二"
        },
        {
          "level": 3,
          "title": "任务三",
          "slug": "任务三"
        },
        {
          "level": 2,
          "title": "poi",
          "slug": "poi"
        },
        {
          "level": 2,
          "title": "w7",
          "slug": "w7"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "如何开发一个可爱的CLI（一）",
      "frontmatter": {
        "date": "2018-03-15T20:44:40.000Z",
        "tags": [
          "JavaScript",
          "Prototype"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-3-15-how-to-write-a-cute-cli-part-1.html",
      "relativePath": "_posts/2018-3-15-how-to-write-a-cute-cli-part-1.md",
      "key": "v-61f0142a",
      "path": "/2018/03/16/how-to-write-a-cute-cli-part-1/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "预热",
          "slug": "预热"
        },
        {
          "level": 2,
          "title": "实战",
          "slug": "实战"
        },
        {
          "level": 3,
          "title": "基本思路",
          "slug": "基本思路"
        },
        {
          "level": 3,
          "title": "伪代码实现",
          "slug": "伪代码实现"
        },
        {
          "level": 3,
          "title": "技术选型",
          "slug": "技术选型"
        },
        {
          "level": 3,
          "title": "更多",
          "slug": "更多"
        },
        {
          "level": 2,
          "title": "甜点时刻",
          "slug": "甜点时刻"
        },
        {
          "level": 3,
          "title": "SAO",
          "slug": "sao"
        },
        {
          "level": 3,
          "title": "poz",
          "slug": "poz"
        },
        {
          "level": 3,
          "title": "alphax",
          "slug": "alphax"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "当你决定去 revert 一个 merge commit",
      "frontmatter": {
        "date": "2018-04-12T22:00:40.000Z",
        "tags": [
          "Git"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-4-12-when-you-decide-to-revert-a-merge-commit.html",
      "relativePath": "_posts/2018-4-12-when-you-decide-to-revert-a-merge-commit.md",
      "key": "v-147f75aa",
      "path": "/2018/04/13/when-you-decide-to-revert-a-merge-commit/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "准备",
          "slug": "准备"
        },
        {
          "level": 2,
          "title": "分析",
          "slug": "分析"
        },
        {
          "level": 2,
          "title": "解决",
          "slug": "解决"
        },
        {
          "level": 3,
          "title": "本文代码均已放到这个仓库上 git-revert-merge-commit",
          "slug": "本文代码均已放到这个仓库上-git-revert-merge-commit"
        },
        {
          "level": 2,
          "title": "结论",
          "slug": "结论"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "深入 JavaScript 继承原理",
      "frontmatter": {
        "date": "2016-12-20T20:44:40.000Z",
        "tags": [
          "JavaScript"
        ],
        "author": "ULIVZ",
        "location": "Foshan",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2016-12-20-javascript-extend.html",
      "relativePath": "_posts/2016-12-20-javascript-extend.md",
      "key": "v-52a0bf6a",
      "path": "/2016/12/21/javascript-extend/",
      "headers": [
        {
          "level": 2,
          "title": "类",
          "slug": "类"
        },
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "类式继承",
          "slug": "类式继承"
        },
        {
          "level": 3,
          "title": "构造函数式继承",
          "slug": "构造函数式继承"
        },
        {
          "level": 3,
          "title": "组合式继承",
          "slug": "组合式继承"
        },
        {
          "level": 3,
          "title": "原型继承",
          "slug": "原型继承"
        },
        {
          "level": 3,
          "title": "寄生继承",
          "slug": "寄生继承"
        },
        {
          "level": 3,
          "title": "寄生组合式继承",
          "slug": "寄生组合式继承"
        },
        {
          "level": 3,
          "title": "终极版继承",
          "slug": "终极版继承"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "题外话",
          "slug": "题外话"
        }
      ],
      "id": "post",
      "pid": "post"
    },
    {
      "title": "漫长的纪念",
      "frontmatter": {
        "date": "2016-02-08T22:33:40.000Z",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2016-02-08-%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/",
      "relativePath": "_writings/2016-02-08-漫长的纪念/index.md",
      "key": "v-5abc6379",
      "path": "/writings/2016/02/09/%E6%BC%AB%E9%95%BF%E7%9A%84%E7%BA%AA%E5%BF%B5/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "title": "云水河",
      "frontmatter": {
        "date": "2010-10-17T22:33:40.000Z",
        "tags": "散文",
        "author": "ULIVZ",
        "location": "Hubei",
        "layout": "Post",
        "permalink": "/writings/:year/:month/:day/:slug"
      },
      "regularPath": "/_writings/2010-10-17-%E4%BA%91%E6%B0%B4%E6%B2%B3.html",
      "relativePath": "_writings/2010-10-17-云水河.md",
      "key": "v-378733bd",
      "path": "/writings/2010/10/18/%E4%BA%91%E6%B0%B4%E6%B2%B3/",
      "id": "writing",
      "pid": "writing"
    },
    {
      "frontmatter": {
        "layout": "Layout"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/"
    },
    {
      "frontmatter": {
        "layout": "Layout"
      },
      "regularPath": "/archive/",
      "key": "v-9e6f27fc",
      "path": "/archive/"
    },
    {
      "frontmatter": {
        "layout": "IndexWriting"
      },
      "regularPath": "/writings/",
      "key": "v-78029643",
      "path": "/writings/"
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "JavaScript | tag"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "DOM | tag"
      },
      "regularPath": "/tag/DOM/",
      "key": "v-3258de12",
      "path": "/tag/DOM/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "散文 | tag"
      },
      "regularPath": "/tag/%E6%95%A3%E6%96%87/",
      "key": "v-589151f9",
      "path": "/tag/散文/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "CLI | tag"
      },
      "regularPath": "/tag/CLI/",
      "key": "v-3259de4e",
      "path": "/tag/CLI/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "Prototype | tag"
      },
      "regularPath": "/tag/Prototype/",
      "key": "v-52d26997",
      "path": "/tag/Prototype/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "Git | tag"
      },
      "regularPath": "/tag/Git/",
      "key": "v-32555732",
      "path": "/tag/Git/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "Page 2 | post"
      },
      "regularPath": "/page/2/",
      "key": "v-8fdafa70",
      "path": "/page/2/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "Page 2 | writing"
      },
      "regularPath": "/writings/page/2/",
      "key": "v-5bdd03cc",
      "path": "/writings/page/2/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterClassifier",
        "title": "Page 2 - 散文 | tag"
      },
      "regularPath": "/tag/%E6%95%A3%E6%96%87/page/2/",
      "key": "v-2ba049a4",
      "path": "/tag/散文/page/2/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Blog",
        "link": "/"
      },
      {
        "text": "Writings",
        "link": "/writings/"
      },
      {
        "text": "Tags",
        "link": "/tag/"
      }
    ],
    "footer": {
      "contact": [
        {
          "type": "github",
          "link": "https://github.com/ulivz"
        },
        {
          "type": "twitter",
          "link": "https://twitter.com/_ulivz"
        }
      ],
      "copyright": [
        {
          "text": "Privacy Policy",
          "link": "https://policies.google.com/privacy?hl=en-US"
        },
        {
          "text": "MIT Licensed | Copyright © 2018-present Vue.js",
          "link": ""
        }
      ]
    }
  }
}