/**
 * Generated by "vuepress-plugin-blog"
 */
export default {
  "tag": {
    "JavaScript": {
      "scope": "tag",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-1b9ad2c6",
        "v-c650be3a",
        "v-c44598e2",
        "v-61f0142a",
        "v-52a0bf6a"
      ]
    },
    "DOM": {
      "scope": "tag",
      "path": "/tag/DOM/",
      "pageKeys": [
        "v-c650be3a"
      ]
    },
    "散文": {
      "scope": "tag",
      "path": "/tag/散文/",
      "pageKeys": [
        "v-1ef79381",
        "v-73974a15",
        "v-7d17ff8f",
        "v-b17f4bd4",
        "v-5abc6379",
        "v-378733bd"
      ]
    },
    "CLI": {
      "scope": "tag",
      "path": "/tag/CLI/",
      "pageKeys": [
        "v-2cb10deb"
      ]
    },
    "Prototype": {
      "scope": "tag",
      "path": "/tag/Prototype/",
      "pageKeys": [
        "v-61f0142a"
      ]
    },
    "Git": {
      "scope": "tag",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-147f75aa"
      ]
    }
  }
}