/**
 * Generated by "vuepress-plugin-blog"
 */
export default {
  "post": function anonymous(page
) {
return page.pid === "post" && page.id === "post"
},
  "archive": function anonymous(page
) {
return page.pid === "archive" && page.id === "archive"
},
  "writing": function anonymous(page
) {
return page.pid === "writing" && page.id === "writing"
},
  "tag": function clientFrontmatterClassifierPageFilter(page, keys, value) {
    return keys.some(key => {
        const _value = page.frontmatter[key];
        if (Array.isArray(_value)) {
            return _value.some(i => i === value);
        }
        return _value === value;
    });
},
}