/**
 * Generated by "vuepress-plugin-blog"
 */
export default [
  {
    "pid": "post",
    "id": "post",
    "paginationPages": [
      {
        "path": "/",
        "interval": [
          0,
          4
        ]
      },
      {
        "path": "/page/2/",
        "interval": [
          5,
          7
        ]
      }
    ]
  },
  {
    "pid": "archive",
    "id": "archive",
    "paginationPages": []
  },
  {
    "pid": "writing",
    "id": "writing",
    "paginationPages": [
      {
        "path": "/writings/",
        "interval": [
          0,
          4
        ]
      },
      {
        "path": "/writings/page/2/",
        "interval": [
          5,
          6
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "JavaScript",
    "paginationPages": [
      {
        "path": "/tag/JavaScript/",
        "interval": [
          0,
          4
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "DOM",
    "paginationPages": [
      {
        "path": "/tag/DOM/",
        "interval": [
          0,
          1
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "散文",
    "paginationPages": [
      {
        "path": "/tag/散文/",
        "interval": [
          0,
          4
        ]
      },
      {
        "path": "/tag/散文/page/2/",
        "interval": [
          5,
          6
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "CLI",
    "paginationPages": [
      {
        "path": "/tag/CLI/",
        "interval": [
          0,
          1
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "Prototype",
    "paginationPages": [
      {
        "path": "/tag/Prototype/",
        "interval": [
          0,
          1
        ]
      }
    ]
  },
  {
    "pid": "tag",
    "id": "Git",
    "paginationPages": [
      {
        "path": "/tag/Git/",
        "interval": [
          0,
          1
        ]
      }
    ]
  }
]